[package]
name = "evr"
version = "0.1.1"
authors = ["syn <isaqtm@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.33"
serde = "1"
toml = "0.5"
serde_derive = "1"
log = "0.4"
env_logger = "0.7.1"
wait-timeout = "0.1.5"
lazy_static = "1.4.0"
nix = "0.16"
